<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $page
     */
    public function findLatest($page = 1, $items = 10)
    {
        $page = (int) $page;
        $items = (int) $items;
        $firstResultIndex = ($page - 1) * $items;
        $maxResults = $items;
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Post p
                WHERE p.created_on <= :now
                ORDER BY p.created_on DESC
            ')
            ->setParameter('now', new \DateTime())
            ->setFirstResult($firstResultIndex)
            ->setMaxResults($items);
        $posts = $query->getResult();
        return $posts;
    }
}
