<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function queryLatest()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Post p
                WHERE p.created_on <= :now
                ORDER BY p.created_on DESC
            ')
            ->setParameter('now', new \DateTime())
            ;
    }

    /**
     * @param int $page
     *
     * @return Pagerfanta
     */
    public function findLatest($page = 1, $items = 10)
    {
        $ormAdapter = new DoctrineORMAdapter($this->queryLatest(), false);
        $posts = $ormAdapter->getSlice(($page - 1) * $items, $items);
        return $posts;
    }
}
